### PR TITLE
Added unit test.

### PR DESCRIPTION
**Pull request by wrightt**
Implemented misc cleanups to support Linux.
Added a basic unit test.

### CODE REVIEW

**Comment by pmeenan** [comment]
I just pulled in all of the relevant fixes except for the unit test.  Let me know if that still looks good and I can pull that in as well.  The rest should be ready to go though.

**Comment by wrightt** [comment]
Thanks.  I had to move the tests to straighten out the import paths.  I'm not sure why my merge 8d054a2 looks so ugly; I think you can simply cherry-pick the "Move test*" 48fdd30.

**Comment by pmeenan** [comment]
I pulled in the unit tests.  I had to make a small change to the test_exec one to explicitly call python because it wouldn't work on Windows othwerwise but let me know if that breaks something on your end.  The import test didn't work on Windows either (ImportError: cannot import name visualmetrics) but I'll worry about that in a bit.

**Comment by wrightt** [comment]
LGTM.

**Pull request closed without merging**
